### ISSUE TITLE
Error. (1.16.1)

### ISSUE THREAD

**Issue by WayPlay** [Tutorialwork/WebAdmin#1]
```
> [21:15:44] [Server thread/INFO]: [WebAdmin] Could connect to mysql database: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
> [21:15:44] [Server thread/ERROR]: Error occurred while enabling WebAdmin v1.1 (Is it up to date?)
java.lang.NullPointerException: null
at de.tutorialwork.webadmin.utils.MySQLConnect.update(MySQLConnect.java:52) ~[?:?]
at de.tutorialwork.webadmin.main.Main.initPlugin(Main.java:157) ~[?:?]
at de.tutorialwork.webadmin.main.Main.onEnable(Main.java:35) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:489) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:403) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:439) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:811) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:165) ~[spigot-1.16.1.jar:git-Spigot-758abbe-3f0c333]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by Tutorialwork** [comment]
This error is caused by wrong credentials for the mysql database in the mysql.yml file.
